// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using komikaan.FileDetector.Contexts;

#nullable disable

namespace komikaan.FileDetector.Migrations
{
    [DbContext(typeof(SupplierContext))]
    [Migration("20240707123946_Mark")]
    partial class Mark
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("komikaan.Common.Models.SupplierConfiguration", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("DataType")
                        .HasColumnType("integer")
                        .HasColumnName("data_type");

                    b.Property<bool>("DownloadPending")
                        .HasColumnType("boolean")
                        .HasColumnName("download_pending");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<TimeSpan>("PollingRate")
                        .HasColumnType("interval")
                        .HasColumnName("polling_rate");

                    b.Property<int>("RetrievalType")
                        .HasColumnType("integer")
                        .HasColumnName("retrieval_type");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Name")
                        .HasName("pk_supplier_configurations");

                    b.ToTable("supplier_configurations", (string)null);
                });

            modelBuilder.Entity("komikaan.Common.Models.SupplierTypeMapping", b =>
                {
                    b.Property<int>("ListedType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("listed_type");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ListedType"));

                    b.Property<int>("NewType")
                        .HasColumnType("integer")
                        .HasColumnName("new_type");

                    b.Property<string>("SupplierConfigurationName")
                        .HasColumnType("text")
                        .HasColumnName("supplier_configuration_name");

                    b.HasKey("ListedType")
                        .HasName("pk_supplier_type_mapping");

                    b.HasIndex("SupplierConfigurationName")
                        .HasDatabaseName("ix_supplier_type_mapping_supplier_configuration_name");

                    b.ToTable("supplier_type_mapping", (string)null);
                });

            modelBuilder.Entity("komikaan.Common.Models.SupplierTypeMapping", b =>
                {
                    b.HasOne("komikaan.Common.Models.SupplierConfiguration", null)
                        .WithMany("Mapping")
                        .HasForeignKey("SupplierConfigurationName")
                        .HasConstraintName("fk_supplier_type_mapping_supplier_configurations_supplier_conf");
                });

            modelBuilder.Entity("komikaan.Common.Models.SupplierConfiguration", b =>
                {
                    b.Navigation("Mapping");
                });
#pragma warning restore 612, 618
        }
    }
}
