// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using komikaan.FileDetector.Contexts;

#nullable disable

namespace komikaan.FileDetector.Migrations
{
    [DbContext(typeof(SupplierContext))]
    [Migration("20240830210523_AddLastCheckedAndETags")]
    partial class AddLastCheckedAndETags
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("komikaan.Common.Models.SupplierConfiguration", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("DataType")
                        .HasColumnType("integer")
                        .HasColumnName("data_type");

                    b.Property<bool>("DownloadPending")
                        .HasColumnType("boolean")
                        .HasColumnName("download_pending");

                    b.Property<string>("ETag")
                        .HasColumnType("text")
                        .HasColumnName("e_tag");

                    b.Property<Guid>("ImportId")
                        .HasColumnType("uuid")
                        .HasColumnName("import_id");

                    b.Property<DateTimeOffset?>("LastAttempt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt");

                    b.Property<DateTimeOffset?>("LastChecked")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_checked");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<Guid>("LatestSuccesfullImportId")
                        .HasColumnType("uuid")
                        .HasColumnName("latest_succesfull_import_id");

                    b.Property<TimeSpan>("PollingRate")
                        .HasColumnType("interval")
                        .HasColumnName("polling_rate");

                    b.Property<int>("RetrievalType")
                        .HasColumnType("integer")
                        .HasColumnName("retrieval_type");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Name")
                        .HasName("pk_supplier_configurations");

                    b.ToTable("supplier_configurations", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
